# Generated by Django 6.0 on 2026-01-08 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty'), ('student', 'Student'), ('staff', 'Staff'), ('alumni', 'Alumni')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='verification_type',
            field=models.CharField(choices=[('student_id', 'Student ID Card'), ('faculty_id', 'Faculty ID Card'), ('staff_id', 'Staff ID Card'), ('certificate', 'Certificate'), ('others', 'Others')], max_length=30),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('education_details', models.TextField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_member', to='accounts.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
