# Generated by Django 6.0 on 2026-01-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, help_text='e.g. 2008-09', max_length=20, null=True),
        ),
    ]
