# Generated by Django 6.0 on 2026-02-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_alumni_graduation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='graduation_year',
            field=models.PositiveIntegerField(),
        ),
    ]
