# Generated by Django 6.0 on 2026-02-14 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_alumni_graduation_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='education_details',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g. Ph.D., M.Sc., B.Sc.', max_length=100)),
                ('major', models.CharField(help_text='e.g. Computer Science, Applied Physics', max_length=200)),
                ('institute', models.CharField(help_text='e.g. University of Dhaka', max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('passing_year', models.PositiveIntegerField(help_text='Year of completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to='accounts.profile')),
            ],
            options={
                'verbose_name_plural': 'Education Records',
                'ordering': ['-passing_year'],
            },
        ),
    ]
