# Generated by Django 6.0 on 2026-02-25 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_faculty_education_details_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1-1', '1st Year 1st Semester'), ('1-2', '1st Year 2nd Semester'), ('2-1', '2nd Year 1st Semester'), ('2-2', '2nd Year 2nd Semester'), ('3-1', '3rd Year 1st Semester'), ('3-2', '3rd Year 2nd Semester'), ('4-1', '4th Year 1st Semester'), ('4-2', '4th Year 2nd Semester')], max_length=10)),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('result_status', models.CharField(choices=[('promoted', 'Promoted'), ('not promoted', 'Not Promoted'), ('withdrawn', 'Withdrawn')], default='promoted', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to='accounts.student')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
