# Generated by Django 6.0 on 2026-02-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_semesterresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, editable=False, help_text='Automatically calculated from session (e.g. 2008-09 → 1)', max_length=10),
        ),
    ]
