# Generated by Django 6.0 on 2026-02-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('general', 'General Notice'), ('exam', 'Exam & Result'), ('admission', 'Admission Notice'), ('event', 'Event & Seminar'), ('scholarship', 'Scholarship'), ('job', 'Job Notice'), ('other', 'Other')], default='general', max_length=20),
        ),
    ]
